on: push
name: Build and deploy GH Pages
jobs:
  build_and_deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: master
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: a2sysml/a2sysml.github.io
      # other deploy does not work
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .